### ISSUE TITLE
Request:  Include text of GPLv2+ with the source files

### ISSUE THREAD

**Issue by gbcox** [njh/perl-musicbrainz-discid#7]
Hello,

I'm packaging MusicBrainz-DiscID to be shipped as part of the Fedora
Distribution and upon package review noticed a license issue.  If you would
consider making the appropriate annotations it would be greatly
appreciated.  Here is a snippet from the Fedora Guidelines that explain the
situation.  If you have any questions please let me know.  Thank you very
much.

If the source package includes the text of the license(s) in its own file,
then that file, containing the text of the license(s) for the package must
be included in %license. If the source package does not include the text of
the license(s), the packager should contact upstream and encourage them to
correct this mistake.

In cases where the upstream has chosen a license that requires that a copy
of the license text be distributed along with the binaries and/or source
code, but does not provide a copy of the license text (in the source tree,
or in some rare cases, anywhere), the packager should do their best to
point out this confusion to upstream. This sometimes occurs when an
upstream project’s only reference to a license is in a README (where they
simply say "licensed under the FOO license"), on their website, or when
they simply do not check a copy of the license into their Source tree.
Common licenses that require including their texts with all derivative
works include ASL 2.0, EPL, BSD and MIT. Packagers should point out to
upstream that by not including a proper full license text, they are making
it difficult or impossible for anyone to comply with their desired license
terms.

**Comment by njh** [comment]
I have changed the license to MIT and included the full license test in LICENSE.md: 
fb02f2f53acc5acc0f194d94975b02a78ac6985b

I have released Version 0.05 with the new license:
https://github.com/njh/perl-musicbrainz-discid/releases/tag/0.05

**Comment by gbcox** [comment]
Hi Nicholas,
I downloaded the tarball from here:  https://metacpan.org/release/NJH/MusicBrainz-DiscID-0.05

and I don't see the LICENSE.md file 

I do see where you changed the other files, but the license didn't make it into the metacpan archive.

**Comment by njh** [comment]
Sorry, I messed up the release.

Here is a new release that should fix it:
https://github.com/njh/perl-musicbrainz-discid/releases/tag/0.06

Or on metacpan.org:
https://metacpan.org/release/NJH/MusicBrainz-DiscID-0.06
